app = "falco-app"
primary_region = "scl"

[build]

[env]
  NODE_ENV = "production"
  DB_PATH = "/data/app.db"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = "falco_data"
  destination = "/data"
